project_name: terradrift
builds:
  - id: terradrift-server
    main: ./terradrift-server
    binary: terradrift-server
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
  - id: terradrift-cli
    main: ./terradrift-cli
    binary: terradrift-cli
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - --platform=linux/amd64
    image_templates:
      - rootsami/{{ .ProjectName }}:{{ .Version }}-amd64
    use: buildx
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - --platform=linux/arm64
    image_templates:
      - rootsami/{{ .ProjectName }}:{{ .Version }}-arm64
    use: buildx
docker_manifests:
- name_template: rootsami/{{ .ProjectName }}:{{ .Version }}
  image_templates:
    - rootsami/{{ .ProjectName }}:{{ .Version }}-amd64
    - rootsami/{{ .ProjectName }}:{{ .Version }}-arm64
- name_template: rootsami/{{ .ProjectName }}:latest
  image_templates:
    - rootsami/{{ .ProjectName }}:{{ .Version }}-amd64
    - rootsami/{{ .ProjectName }}:{{ .Version }}-arm64
