stacks:
  - name: core-staging
    path: gcp/core-staging

  - name: core-production
    path: aws/core-production

  - name: api-staging
    path: gcp/api
    tfvars: environments/staging.tfvars
    backend: environments/staging.hcl

  - name: api-production
    path: gcp/api
    tfvars: environments/production.tfvars
    backend: environments/production.hcl
