{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "terradrift.fullname" . }}-servicemonitor
  labels:
    {{- include "terradrift.labels" . | nindent 8 }}
spec:
  selector:
    matchLabels:
      {{- include "terradrift.labels" . | nindent 8 }}
  endpoints:
  - port: http
    path: {{ .Values.serviceMonitor.metricPath }}
{{- end }}
