name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
          cache: true
      - run: make deps
      - run: make test
      - run: make build
      - uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PAT }}
      - uses: goreleaser/goreleaser-action@v2
        with:
          version: ${{ github.ref_name }}
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
